<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-05-24T09:53:48+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Ravfestival',
    'locale' => 'da_DK',
    'version_installed' => '5.7.5.7',
    'misc' => array(
        'access_entity_updated' => 1463733831,
        'latest_version' => '5.7.5.6',
        'do_page_reindex_check' => false,
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'accessibility' => array(
        'toolbar_titles' => false,
        'toolbar_large_font' => false,
        'display_help_system' => false,
    ),
);
