<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-05-20T10:43:51+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Ravfestival',
    'locale' => 'da_DK',
    'version_installed' => '5.7.5.7',
    'misc' => array(
        'access_entity_updated' => 1463733831,
        'latest_version' => '5.7.5.6',
        'do_page_reindex_check' => false,
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
);
